
name: V2freeCheckin
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  check-in:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 降级到兼容版本
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.28.2 urllib3==1.26.0 six==1.16.0
          pip install -r requirements.txt
      - name: Checkin
        run: |
          python main.py --username ${{ secrets.USER }} --password ${{ secrets.PWD }} \
            --remail=${{secrets.remail}} --semail=${{secrets.semail}} --secode=${{secrets.secode}}
