
name: V2freeCheckin
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  check-in:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall "six==1.16.0" "urllib3<2.0.0" requests
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      - name: Checkin
        run: |
          # 原有签到脚本保持不变
          python main.py --username ${{ secrets.USER }} --password ${{ secrets.PWD }} \
            --remail=${{secrets.remail}} --semail=${{secrets.semail}} --secode=${{secrets.secode}}
